services:
  app:
    build:
      context: .
      target: prod
    ports:
      - ${PORT}:${PORT}
      - ${PEER_PORT}:${PEER_PORT}
    command: pm2-runtime start --name=api index.js
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - PEER_PORT=${PEER_PORT}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}

  db:
    image: redis:7.2.5
